### PR TITLE
Ast type hints

### LINKED ISSUE #171: Type hints for ast.py
I guess adding type hints can help using developing/debugging. For example: I was not clear to me what is `tlist`.

```
def ahf(tlist) -> int:
    """Ratio of private/protected attributes to all attributes in a class.
    :rtype: float
    """
    declaration = tlist[0][1].filter(javalang.tree.FieldDeclaration)
    fields = list(field for field in declaration)
    hidden = 0
    total = 0
    for path, node in fields:
        del path
        if 'private' in node.modifiers or 'protected' in node.modifiers:
            hidden += 1
        total += 1
    if total == 0:
        return 0
    return hidden / total
```

Suggestion:

```
def ahf(tlist: list[tuple[javalang.tree.ClassDeclaration]]) -> int:
```

### PR DESCRIPTION
**Pull request by ilnarkhasanov**
Closes #171

### CODE REVIEW

**Comment by yegor256** [comment]
@ilnarkhasanov is it possible to configure `pylint` or maybe some other code analysis tool such that it catches Python code without type hints? If we add such a tool to the build, it will help us avoid similar problems in the future.

**Comment by yegor256** [comment]
@ilnarkhasanov maybe you can just add `mypy` to our existing `lint.sh` script, where we call `pylint`. There is no need to create a separate Github Actions job, I believe.

**Comment by ilnarkhasanov** [comment]
@yegor256 I have added `mypy` to the `lint.sh`. Could you check, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@ilnarkhasanov thanks!

**Pull request merged**
