### PR TITLE
Implemented test for irca feature

### PR DESCRIPTION
**Pull request by zaqbez39me**
Test for Impact Ratio by Commit Authors (IRCA) in #226

### CODE REVIEW

**Comment by zaqbez39me** [comment]
@yegor256 please, check this test out

**Comment by yegor256** [comment]
@zaqbez39me looks good, but `make` fails (see above). Also, to disable a test, it's better to do `exit 0` at the beginning of the script, instead of commenting it all out

**Comment by zaqbez39me** [comment]
@yegor256 fixed the test disabling method. Please, check my reasoning about make in #259

**Comment by zaqbez39me** [comment]
@yegor256 after providing access for execution for test-irca.sh and adding the stub irca.sh, I met with another error that is not directly connected with my part. Maybe, this error in pipline was before in master branch

**Comment by yegor256** [comment]
@zaqbez39me the master branch has a clean build: https://github.com/yegor256/cam/actions/workflows/make.yml

**Comment by zaqbez39me** [comment]
@yegor256 as I see this error occurs because of my stub and `test-measure-file.sh` conflict. If I make my stub return "IRCA 0.000" then the `test-measure-file.sh` fails with the error 'Exactly 52 metrics were expected, but 53 were actually collected' because of hardcoded 52 constant in it.

**Comment by zaqbez39me** [comment]
I had to add stub because of another test that checks following:
If test exists then the script also must exist

**Comment by yegor256** [comment]
@zaqbez39me maybe you should change the number in the `test-measure-file.sh`?

**Comment by zaqbez39me** [comment]
@yegor256 maybe, I should better fix the hardcoded value with calculated in separate pull request and then rerun all the pipelines again?

**Comment by yegor256** [comment]
@zaqbez39me sounds good!

**Comment by zaqbez39me** [comment]
@yegor256 please, check it out. Now everything works fine

**Comment by yegor256** [comment]
@zaqbez39me thanks!

**Pull request merged**
