### PR TITLE
Add homebrew requirements

### PR DESCRIPTION
**Pull request by timur-harin**
@yegor256 

In this pull request, I have added a new file named `brew-requirements.txt` which contains a list of packages that are required for this repository to function properly on macOS. This file is specifically designed for macOS users who want to install all the necessary packages using Homebrew.

### CODE REVIEW

**Comment by yegor256** [comment]
@timur-harin maybe it's better modify our `install.sh` script to make it understand the presence of `brew` and use to install dependencies?

**Comment by timur-harin** [comment]
@yegor256 
Do you mean?

```
if command -v brew &> /dev/null
then
    echo "Homebrew is installed."
else
    echo "Homebrew is not installed."
fi
```

**Comment by yegor256** [comment]
@timur-harin yes, something like this. Currently, in our script, we check for Linux. If it's linux, we try `apt-get install`. We can also check for macOS and run `brew install` if it's Mac and homebrew is present.

**Comment by timur-harin** [comment]
Continue in PR #337

**Pull request closed without merging**
