### PR TITLE
Add script to delete not utf8 java files and run it

### PR DESCRIPTION
**Pull request by timur-harin**
@yegor256 
In [issue 169](https://github.com/yegor256/cam/issues/169) you mentioned that you should **delete not UTF8 source Java files**

I think that **we need** also to have this **script** with showing which files were deleted which I put **in the help folder**

### CODE REVIEW

**Comment by yegor256** [comment]
@timur-harin also, when your branch is ready, run `make test`

**Comment by timur-harin** [comment]
@yegor256 are you talking about changing a file `040-delete-unparseable.sh` or creating a new one? 
If about new one, which number I can take in the start of the file name of script?

**Comment by yegor256** [comment]
@timur-harin make a new one and call it `041-delete-non-unicode.sh`

**Comment by timur-harin** [comment]
@yegor256 I added a test and moved the script

**Comment by yegor256** [comment]
@timur-harin why did you delete files from the `fixtures/` directory? I believe, we need them.

**Comment by timur-harin** [comment]
@yegor256, in issue there is "delete non-UTF8 source Java files" 
I understood that like 

>  files that make up a project. They contain the code written by the developers and are used to build the final executable or deployable software

So I had to delete not UTF8 Java files in project

**Comment by timur-harin** [comment]
@yegor256 If I am not right, correct me

**Comment by yegor256** [comment]
@timur-harin the objective of this filter is to delete files that have wrong encoding inside, which is not UTF-8 and not ASCII

**Comment by yegor256** [comment]
@timur-harin it was implemented in #285

**Pull request closed without merging**
