### PR TITLE
Added metric RAF and tests for it

### LINKED ISSUE #129: Relative Age of File (RAF)
Every file has the time of appearance in the repository. If we place all these values on a time line, the time of a given file will be somewhere in the middle. RAF is the number between 0 and 1, which shows where exactly is the file's time on the timeline.

### PR DESCRIPTION
**Pull request by zaqbez39me**
Added metric RAF (Relative Age of File) that shows the position of given file first appearance on on the repository timeline. This metric is bounded by 0.0, which is the repo creation time, and 1.0 ,which is current moment.

Closes #129

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@zaqbez39me please, put the license on top of all `.sh` files

**Comment by zaqbez39me** [comment]
@yegor256 Done

**Comment by yegor256** [comment]
@zaqbez39me thanks!

**Pull request merged**
