### PR TITLE
Added nop metric

### PR DESCRIPTION
**Pull request by Zener085**
~ Added new function `nop` to `ast.py` file that calculates number of polymorphic methods in class. The function counts polymorphic methods in main class and ignores any methods inside nested classes.
~ Added calling function in `ast.py` and `test-ast.sh` to test the metric

### CODE REVIEW

**Comment by Zener085** [comment]
@yegor256 This is issue #118

**Comment by yegor256** [comment]
@Zener085 thanks for your contribution! Did you run `make test` locally? Dit it work?

**Comment by Zener085** [comment]
@yegor256 Yes, everything was fine during local testing

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@Zener085 thanks!

**Pull request merged**
