### PR TITLE
new metric: authors per file

### PR DESCRIPTION
**Pull request by rliskunov**
@yegor256  could you please help adapt the code for the rest of the codebase? In my changes we can get the list and the number of people who changed the any file from repository. The section `test for TypeTest.java` shows an example of work.

### CODE REVIEW

**Comment by yegor256** [comment]
@rliskunov well, your Python script will be called like this: `authors.py Foo.java metrics`. It is expected that it prints something like this to the `metrics` file:

```
authors 5 Number of Committers/Authors
```

Here, `5` is the number you calculate.

**Comment by rliskunov** [comment]
@yegor256 I have good news. I run the script as you said and get the value of the authors, so for example `authors.py TypeTest.java metrics`:
```text
authors 6 Number of Committers/Authors
```
Unfortunately, in my implementation I am forced to pass the repository name through the `url` variable. Sorry for asking a silly question, but could you please tell me how you did it?

**Comment by rliskunov** [comment]
@yegor256 with the addition of a `pylint`, additional refactoring had to be done. I also added `W0612` to the exception, as I am not sure if this warning is correct:
```text
Unused variable 'path' (unused-variable)
```

**Comment by yegor256** [comment]
@rliskunov well, I don't think you need the URL. When the file is provided to you, you can just do `git log $file` and everything will be printed.

**Comment by rliskunov** [comment]
@yegor256 I realized my mistake. The changes I made involve analyzing the repository without your bash scripts. I am not claiming that my solution is correct, but it might be worth giving them up and trying the [PyDriller](https://pydriller.readthedocs.io/en/latest/) library. This will solve the Python-style problem. What do you think about this?

Anyway, thanks for the advice. At the moment I will solve the issue through `git log`.

**Comment by yegor256** [comment]
@rliskunov I suggest we split this pull request into two parts. You are making two different sets of changes here, which makes it difficult to merge.

**Comment by rliskunov** [comment]
@yegor256 okay, I'll do it.

**Pull request closed without merging**
