### PR TITLE
Fixed make pipeline for Linux

### LINKED ISSUE #368: make env failing because of flake8
I was fixing the pipelines and encountered the following error (both on macOS and Ubuntu):
```
make lint

+++ lint +++

Citation metadata are valid according to schema version 1.2.0.
mypy.ini: No [mypy] section in config file
Success: no issues found in 8 source files
/home/nai1ka/cam/venv/lib/python3.10/site-packages/sympy/polys/numberfields/resolvent_lookup.py: "pyflakes[F]" failed during execution due to RecursionError('maximum recursion depth exceeded')
Run flake8 with greater verbosity to see more details
make: *** [Makefile:92: lint] Error 1
```

Moreover, I get the same error when running `flake8 --max-line-length=140 .` manually.

I will attempt to fix this soon, but anyone else is welcome to address it in the meantime :)

### PR DESCRIPTION
**Pull request by nai1ka**
I have fixed the `make` pipeline for Linux. Also now venv is created in `install` step and used in all other steps, no more externally-managed enviroment error.

image
Also, the link to the pipeline run: https://github.com/nai1ka/cam/actions/runs/10967188167/job/30456581955

Also resolves #368 (the problem was that `flake8` was scanning the `venv` folder)

### CODE REVIEW

**Comment by nai1ka** [comment]
However, sometimes (randomly) it still fails due to
```
tlmgr: Remote database (revision 72321 of the texlive-scripts package)
seems to be older than the local installation (rev 72328 of
texlive-scripts); please use a different mirror and/or wait a day or two.
```
As I understood, it happens if mirror is being updated during the pipeline run

@yegor256, what do you think? Maybe we can use some other mirror, or just rerun the pipeline...

**Comment by yegor256** [comment]
@nai1ka I believe, this `tlmgr: Remote database` failure is not related to this PR and may be solved in another one, maybe later

**Comment by yegor256** [comment]
@nai1ka what about this? https://github.com/yegor256/cam/actions/runs/10967602594/job/30457613493?pr=369

**Comment by nai1ka** [comment]
@yegor256 I wanted to fix it in a separate PR. Or do you want me to fix it in this PR?

**Comment by yegor256** [comment]
@nai1ka thanks for this one! Please, try to fix macOS problem in a separate PR

**Pull request merged**
