### PR TITLE
new metric: authors per file

### PR DESCRIPTION
**Pull request by rliskunov**
@yegor256 I corrected what we discussed earlier. Look please

### CODE REVIEW

**Comment by rliskunov** [comment]
I propose to solve the problem with static analysis in the next pull request.

**Comment by yegor256** [comment]
@rliskunov looks good, but why in the `ast-metrics.py` file? This metric has nothing to do with AST, I believe :) I suggest you make another file `authors.py` and place just your metric there.

**Comment by rliskunov** [comment]
@yegor256 thanks for the comment, I made the wrong conclusion from the previous discussion. What do you think now?

**Comment by yegor256** [comment]
@rliskunov looks good to me, I'm ready to merge, but CI complains. Can you please check why?

**Comment by rliskunov** [comment]
@yegor256 it seems to me that the problem here is the same as in the neighboring pull request, because for the file `authors.py` checks are not triggered :(

**Comment by yegor256** [comment]
@rliskunov I merged, thanks! Now, I believe, would be great to fix all lint issues and submit a new PR with fixes. Can you please do this?

**Pull request merged**
