### PR TITLE
Add getter and setter metric

### PR DESCRIPTION
**Pull request by padjal**
This pull requests adds one more metric to the repo - Getters and setters.

### CODE REVIEW

**Comment by yegor256** [comment]
@padjal try to run `make test` locally

**Comment by padjal** [comment]
Tests should be fixed now.

**Comment by yegor256** [comment]
@padjal most probably you should do `chmod a+x metrics/getset.py` (the same for the test)

**Comment by padjal** [comment]
I changed the permissions of the file. Error now is: 
image

**Comment by yegor256** [comment]
@padjal I suspect that your `.py` is missing the [shebang] (https://en.wikipedia.org/wiki/Shebang_(Unix)) header, that's why it's being executed as a Bash script (and fails)

**Comment by padjal** [comment]
@yegor256  Added the shebang (I think). Please approve

**Comment by padjal** [comment]
@yegor256  Do you have any suggestions what might be the problem?

**Comment by yegor256** [comment]
@padjal try to run `make test` locally. Does it pass for you?

**Comment by padjal** [comment]
No, make tests doesn't run locally. It crashes with a `Permission denied` error message: 
```bash
metrics/test-getset.sh:
rm: cannot remove '/home/padjal/dev/cam/cam/test-zone/metrics/test-getset.sh/target': Permission denied
make: *** [Makefile:78: test] Error 1
```

I changed the permissions of both the `getset.py` and `test-getset.sh` files:
image
image


What other suggestions do you have?

**Pull request closed without merging**
