### PR TITLE
Removed usage of sudo from test-raf.sh

### LINKED ISSUE #179: The RAF is broken
The changes in tests were made together with logic changes. Now RAF time does not show relative time it actually shows real time of file  existence. Therefore, the time now not in range from 0 to 1.

### PR DESCRIPTION
**Pull request by zaqbez39me**
Fixed the problem with usage of sudo in tests, which is bad practise.

Closes #179

### CODE REVIEW

**Comment by yegor256** [comment]
@zaqbez39me still an error :(

**Comment by zaqbez39me** [comment]
@yegor256 Actually, I do not set the date anywhere in the updated version. However, the error occurs.

**Comment by yegor256** [comment]
@zaqbez39me it's weird. I merged. Let's see how GHA behaves now.

**Comment by zaqbez39me** [comment]
@yegor256 I suppose GHA behaves like this because of caching

**Pull request merged**
