### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by rliskunov**
Visual code improvement according to PEP8 and Dockerfile optimization

### CODE REVIEW

**Comment by yegor256** [comment]
@rliskunov maybe it will be good to add `pep8` call to `Makefile` in order to avoid future problems of the same type?

**Comment by rliskunov** [comment]
@yegor256 thanks for the idea! I added two popular linters `flake8` and `pylint`. I successfully solved all the problems that the first analyzer showed. But now `pylint` demonstrate that code has been rated at 6.30/10. Please see what warnings I can add to the ignore section.

**Comment by yegor256** [comment]
@rliskunov I believe there are merge conflicts :( Please, merge `master` branch into your branch and resolve them. Then, push your branch to GitHub and let me know.

**Comment by rliskunov** [comment]
@yegor256 hope i was able to resolve conflicts. See the changes, please

**Comment by yegor256** [comment]
@rliskunov thanks!

**Pull request merged**
