### PR TITLE
Add brew for main packages install from macos

### PR DESCRIPTION
**Pull request by timur-harin**
@yegor256 
In this pull request, I have added:
- Check for macOS system 
- Check and installation of brew if not installed
- Install steps using brew in `steps/install.sh`

### CODE REVIEW

**Comment by yegor256** [comment]
@timur-harin don't you think that installing homebrew to an innocent user's machine is a bit intrusive? :) They clone our repo, run `make install` and then boom! -- their system has a new system-level component. I think, they will be surprised at best.

**Comment by timur-harin** [comment]
@yegor256 
I agree. So we can make `echo` message, that if `brew` not installed you can download it and put install link?

**Comment by yegor256** [comment]
@timur-harin yes, this will be reasonable. We either 1) use `brew install ...` if `brew` is present, or 2) we say "if you install Homebrew, all necessary packages will be installed automatically by make install"

**Comment by timur-harin** [comment]
@yegor256 
I updated this PR:
- Now it will not install `brew`, only suggest if not found

**Comment by yegor256** [comment]
@timur-harin thanks!

**Pull request merged**
