### PR TITLE
Add number of metrics analyzer 

### PR DESCRIPTION
**Pull request by timur-harin**
@yegor256 
In this PR, I added:
- Complex Java class to check number of metrics
- Check that number is equivalent with number of metrics of simple Java class Foo

Now the result of  `sudo make test TEST=tests/steps/test-measure-file.sh`
```bash
steps/test-measure-file.sh:
👍🏻 Single file measured correctly
👍🏻 Broken syntax measured and error log created
👍🏻 Complex file measured correctly
👍🏻 Number of metrics matches for simple and complex Java files: 62 metrics
```

### CODE REVIEW

**Comment by timur-harin** [comment]
@yegor256 
Please check this important PR for metrics

**Comment by yegor256** [comment]
@timur-harin looks good! However, you broke the structure that we use in all our tests. Don't go outside of the `{...}` layout and don't make your own error message. Just `exit 1` if the test fails. Also, don't modify an existing test, but add your own new test at the bottom.

**Comment by timur-harin** [comment]
@yegor256 
But we had to remove expected in this file what I discussed in Issue #282 

So you suggest creating another file `test-number-of-metrics.sh` with the same logic and return everything back in `test-measure-file.sh` besides analysing the number of metrics?

**Comment by yegor256** [comment]
@timur-harin no need to create a new file. Just take the `test-measure-file.sh` file, remove the line where we check the number of metrics and commit. Then, add a new test at the bottom of this file -- the test that you created.

**Comment by timur-harin** [comment]
@yegor256 
I applied your suggestions:
- Separate test
- All inside {}
- Success message now `👍🏻 Number of metrics matches for simple and complex Java files: 62 metrics`

**Comment by yegor256** [comment]
@timur-harin excellent work, thanks!

**Pull request merged**
